#!/usr/bin/with-contenv bash

log () { echo "[$1] [webflo/docker-mods] "$2""; }
log_info () { log "INFO" "$1"; }
log_error () { log "ERROR" "$1"; }

echo '---------------------------------------'
echo '|  webflo docker mod (webflo-backup)  |'
echo '---------------------------------------'

chmod u+x /webflo/apps/*.sh

if [ -f ${WEBFLO_BACKUP_APP} ]; then
  log_error "App name is not set in env."
  exit 1;
fi

SCRIPT_FILE=/webflo/apps/${WEBFLO_BACKUP_APP}.sh

if !([ -f $SCRIPT_FILE ] && [ -x $SCRIPT_FILE ]); then
  log_error "There is no backup script for app ${WEBFLO_BACKUP_APP}"
  exit 1;
fi

if [ ! -d /backup ]; then
  log_error "Disable backup:  folder /backup does not exists."
  exit 1;
fi

#------------------------------------------------------#

mkdir -p /webflo
touch /var/lock/webflo-backup.lock
chown -R abc:abc /webflo /var/lock/webflo-backup.lock
chmod u+x /webflo/backup.sh
chmod u+r /config/crontabs/abc


CRON=${WEBFLO_BACKUP_CRON:-0 2 * * *}

if [ ${WEBFLO_BACKUP_ENABLED} = true ]; then
  log_info "enabling backup. Setting up cron."
  echo "${CRON} /webflo/backup.sh" > /config/crontabs/abc
else
  log_info "disabling backup. Setting up empty cron."
  echo "" > /config/crontabs/abc
fi

crontab -u abc /config/crontabs/abc
