#!/usr/bin/with-contenv bash

log () { echo "[$1] [webflo/docker-mods] "$2""; }
log_info () { log "INFO" "$1"; }
log_error () { log "ERROR" "$1"; }

echo '---------------------------------'
echo '|  webflo docker mod (appname)  |'
echo '---------------------------------'