#!/usr/bin/with-contenv bash

log () { echo "[$1] [webflo/docker-mods] "$2""; }
log_info () { log "INFO" "$1"; }
log_error () { log "ERROR" "$1"; }

echo '--------------------------------'
echo '|  webflo docker mod (jackett)  |'
echo '--------------------------------'

INDEXERS_DIR=/config/Jackett/Indexers
if [ ! -d "$INDEXERS_DIR" ]; then
  mkdir -p $INDEXERS_DIR
  log_info "adding default indexers..."
  cp /defaults/indexers/*.json $INDEXERS_DIR
  log_info "default indexers added !"
  chmod u+rw $INDEXERS_DIR/*
  chown -R abc:abc /config
fi